### ISSUE TITLE
curl certificates misconfigured in global zone

### ISSUE THREAD

**Issue by mcandre** [joyent/illumos-extra#28]
In the latest SmartOS, the global zone's curl cannot retrieve content over HTTPS, as its SSL certificates are missing.

I tried to install the latest root certs into /etc/ssl/certs/ca-certificates.crt, but curl complains with error numbers 77 or 60, depending on which `-outformat` I try when converting the original PEM file to CRT.

**Comment by bahamat** [comment]
`/etc/ssl/certs/ca-certificates.crt` is intentionally omitted. There are a few options.

1. Use your own trust anchor
2. Copy `/etc/ssl/certs/ca-certificates.crt` from a base-64 zone image
3. Install the SmartOS tools pkgsrc distribution and install `mozilla-certificates`

A valid trust anchor can be in `/etc/ssl/certs/ca-certificates.crt` or specified by the `CURL_CA_BUNDLE` environment variable.

As far as error numbers 60 or 77 returned by curl, the most likely cause is an improperly formatted file, though it's difficult to say without having access to the file myself.

**Comment by mcandre** [comment]
Meh, curl doesn't even know to look for the certificates installed by mozilla-certificates, so I'll stick with unverified HTTPS downloads and hardcoded checksums for now :P

**Comment by bahamat** [comment]
The default configuration will now recognize the mozilla-certificates installed via pkgsrc-tools.

joyent/illumos-joyent@8d38846690
