### ISSUE TITLE
update ntp to ntp-4.2.8p15 from ntp-4.2.8p8

### ISSUE THREAD

**Issue by tozhu** [joyent/illumos-extra#45]
the latest ntp version is ntp-4.2.8p15, current version is ntp-4.2.8p8

follow is the diff for the upgrade, and is tested for compile

diff --git a/ntp/Makefile b/ntp/Makefile
index 0ac92cb..13d527f 100644
--- a/ntp/Makefile
+++ b/ntp/Makefile
@@ -22,7 +22,8 @@
 # Copyright 2019 Joyent, Inc.
 #

-VER =  ntp-4.2.8p8
+VER =  ntp-4.2.8p15

 include ../Makefile.defs

following is the diff for Patches

diff --git a/ntp/Patches/arc4random.patch b/ntp/Patches/arc4random.patch
index 9335340..9b47948 100644
--- a/ntp/Patches/arc4random.patch
+++ b/ntp/Patches/arc4random.patch
@@ -1,6 +1,5 @@
-diff -ur lib/isc/random.c lib/isc/random.c
---- lib/isc/random.c   2014-12-19 11:56:53.000000000 +0000
-+++ lib/isc/random.c   2015-04-08 21:02:23.301311839 +0000
+--- lib/isc/random.c_orig      2020-12-15 09:40:25.156129286 +0000
++++ lib/isc/random.c   2020-12-15 09:42:27.787821312 +0000
 @@ -41,17 +41,6 @@
  static void
  initialize_rand(void)
@@ -57,9 +56,8 @@ diff -ur lib/isc/random.c lib/isc/random.c
  }

  isc_uint32_t
-diff -ur sntp/libevent/arc4random.c sntp/libevent/arc4random.c
---- sntp/libevent/arc4random.c 2014-12-19 11:56:53.000000000 +0000
-+++ sntp/libevent/arc4random.c 2015-04-08 20:59:41.424274901 +0000
+--- sntp/libevent/arc4random.c_orig    2020-12-15 09:45:13.648770558 +0000
++++ sntp/libevent/arc4random.c 2020-12-15 09:46:37.956921662 +0000
 @@ -1,556 +0,0 @@
 -/* Portable arc4random.c based on arc4random.c from OpenBSD.
 - * Portable version by Chris Davis, adapted for Libevent by Nick Mathewson
@@ -617,9 +615,8 @@ diff -ur sntp/libevent/arc4random.c sntp/libevent/arc4random.c
 -      return r % upper_bound;
 -}
 -#endif
-diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
---- sntp/libevent/evutil_rand.c        2014-12-19 11:56:52.000000000 +0000
-+++ sntp/libevent/evutil_rand.c        2015-04-08 21:07:25.994990893 +0000
+--- sntp/libevent/evutil_rand.c_orig   2020-12-15 09:47:45.644374432 +0000
++++ sntp/libevent/evutil_rand.c        2020-12-15 09:53:16.489751822 +0000
 @@ -40,104 +40,26 @@
  #include "util-internal.h"
  #include "evthread-internal.h"
@@ -727,7 +724,7 @@ diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
        return 0;
  }
  #endif
-@@ -145,62 +67,21 @@
+@@ -145,58 +67,17 @@
  static void
  evutil_free_secure_rng_globals_locks(void)
  {
@@ -787,8 +784,3 @@ diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
  }

  void
- evutil_free_secure_rng_globals_(void)
- {
--    evutil_free_secure_rng_globals_locks();
-+      evutil_free_secure_rng_globals_locks();
- }
diff --git a/ntp/Patches/etcfix.patch b/ntp/Patches/etcfix.patch
index 3a10a6b..3fb21f9 100644
--- a/ntp/Patches/etcfix.patch
+++ b/ntp/Patches/etcfix.patch
@@ -1,6 +1,6 @@
---- include/ntp_config.h.orig  Thu May 14 06:34:41 2009
-+++ include/ntp_config.h       Thu May 14 06:15:12 2009
-@@ -10,7 +10,7 @@
+--- include/ntp_config.h_orig  2020-12-15 09:59:29.608754176 +0000
++++ include/ntp_config.h       2020-12-15 10:00:02.755717774 +0000
+@@ -15,7 +15,7 @@
   */
  #ifndef CONFIG_FILE
  # ifndef SYS_WINNT
@@ -9,20 +9,20 @@
  # else /* SYS_WINNT */
  #  define     CONFIG_FILE     "%windir%\\system32\\drivers\\etc\\ntp.conf"
  #  define     ALT_CONFIG_FILE "%windir%\\ntp.conf"
---- libntp/audio.c.orig        Thu May 14 06:34:41 2009
-+++ libntp/audio.c     Thu May 14 06:15:12 2009
-@@ -53,7 +53,7 @@
+--- libntp/audio.c_orig        2020-12-15 10:01:01.291870014 +0000
++++ libntp/audio.c     2020-12-15 10:01:31.639741992 +0000
+@@ -66,7 +66,7 @@
  static struct audio_device device; /* audio device ident */
  #endif /* HAVE_SYS_AUDIOIO_H */
  #ifdef PCM_STYLE_SOUND
 -# define INIT_FILE "/etc/ntp.audio"
 +# define INIT_FILE "/etc/inet/ntp.audio"
- int agc =     SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE */
- int monitor = SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
- int devmask = 0;
---- ntpdate/ntpdate.c.orig     Thu May 14 06:34:41 2009
-+++ ntpdate/ntpdate.c  Thu May 14 06:15:12 2009
-@@ -192,7 +192,7 @@
+
+ static ioctl_arg_T agc                = SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE */
+ static ioctl_arg_T audiomonitor       = SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
+--- ntpdate/ntpdate.c_orig     2020-12-15 10:02:37.046065626 +0000
++++ ntpdate/ntpdate.c  2020-12-15 10:03:04.849615327 +0000
+@@ -179,7 +179,7 @@

  #ifndef KEYFILE
  # ifndef SYS_WINNT
@@ -31,9 +31,9 @@
  # else
  #define KEYFILE       "%windir%\\ntp.keys"
  # endif /* SYS_WINNT */
---- ntpd/refclock_oncore.c     2015-01-03 03:47:48.000000000 +0000
-+++ ntpd/refclock_oncore.c     2015-04-08 05:19:17.841550368 +0000
-@@ -1211,7 +1211,7 @@
+--- ntpd/refclock_oncore.c_orig        2020-12-15 10:03:48.326006011 +0000
++++ ntpd/refclock_oncore.c     2020-12-15 10:04:26.727103584 +0000
+@@ -1213,7 +1213,7 @@

        FILE    *fd;
        char    *cc, *ca, line[100], units[2], device[64];
diff --git a/ntp/Patches/monitor.patch b/ntp/Patches/monitor.patch
deleted file mode 100644
index b460db5..0000000
--- a/ntp/Patches/monitor.patch
+++ /dev/null
@@ -1,29 +0,0 @@
---- libntp/audio.c     Tue Jul  1 18:15:20 2014
-+++ libntp/audio.c.orig        Tue Jul  1 18:15:37 2014
-@@ -55,7 +55,7 @@
- #ifdef PCM_STYLE_SOUND
- # define INIT_FILE "/etc/inet/ntp.audio"
- int agc =     SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE */
--int monitor = SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
-+int audiomonitor =    SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
- int devmask = 0;
- int recmask = 0;
- char cf_c_dev[100], cf_i_dev[100], cf_agc[100], cf_monitor[100];
-@@ -334,7 +334,7 @@
-               /* devmask */
-               i = mixer_name(cf_monitor, devmask);
-               if (i >= 0)
--                      monitor = MIXER_WRITE(i);
-+                      audiomonitor = MIXER_WRITE(i);
-               else
-                       printf("monitor %s not in devmask %#x\n",
-                              cf_monitor, devmask);
-@@ -409,7 +409,7 @@
- # endif
-               l |= r << 8;
-               if (cf_monitor[0] != '\0')
--                      rval = ioctl(ctl_fd, monitor, &l );
-+                      rval = ioctl(ctl_fd, audiomonitor, &l );
-               else
-                       rval = ioctl(ctl_fd, SOUND_MIXER_WRITE_VOLUME,
-                                    &l);
diff --git a/ntp/Patches/openssl.patch b/ntp/Patches/openssl.patch
index 5b2bda4..25383f8 100644
--- a/ntp/Patches/openssl.patch
+++ b/ntp/Patches/openssl.patch
@@ -1,7 +1,7 @@
---- sntp/m4/ntp_openssl.m4.orig        Tue Jul  1 19:32:31 2014
-+++ sntp/m4/ntp_openssl.m4     Tue Jul  1 19:34:46 2014
-@@ -66,6 +66,17 @@
- esac
+--- sntp/m4/ntp_openssl.m4_orig        2020-12-15 10:10:18.520857041 +0000
++++ sntp/m4/ntp_openssl.m4     2020-12-15 10:12:11.138442468 +0000
+@@ -73,6 +73,17 @@
+
  case "$with_crypto:${PKG_CONFIG:+notempty}:${with_openssl_libdir-notgiven}:${with_openssl_incdir-notgiven}" in
   no:*) ;;
 + sunw:*)
diff --git a/ntp/Patches/perl.patch b/ntp/Patches/perl.patch
index 8bef488..2f17110 100644
--- a/ntp/Patches/perl.patch
+++ b/ntp/Patches/perl.patch
@@ -1,6 +1,6 @@
---- configure.ac       2014-07-02 20:25:10.231597249 +0000
-+++ configure.ac       2014-07-02 20:52:06.327098504 +0000
-@@ -131,12 +131,10 @@
+--- configure.ac_orig  2020-12-15 10:06:02.792818880 +0000
++++ configure.ac       2020-12-15 10:08:29.547472840 +0000
+@@ -134,12 +134,10 @@
  AC_ISC_POSIX

@@ -13,8 +13,8 @@
  AC_PATH_PROG([PATH_TEST], [test])
  AS_UNSET([ac_cv_path_PATH_TEST])
  test -z "$CONFIG_SHELL" && CONFIG_SHELL=/bin/sh
-@@ -4302,7 +4300,30 @@
- AC_CONFIG_FILES([tests/ntpd/Makefile])
+@@ -4459,7 +4457,30 @@
+ AC_CONFIG_FILES([tests/sec-2853/Makefile])
  AC_CONFIG_FILES([util/Makefile])

 -perllibdir="${datadir}/ntp/lib"

**Comment by tozhu** [comment]
> the latest ntp version is ntp-4.2.8p15, current version is ntp-4.2.8p8
> 
> follow is the diff for the upgrade, and is tested for compile
> 
> diff --git a/ntp/Makefile b/ntp/Makefile
> index 0ac92cb..13d527f 100644
> --- a/ntp/Makefile
> +++ b/ntp/Makefile
> @@ -22,7 +22,8 @@
> 
> # Copyright 2019 Joyent, Inc.
> -VER = ntp-4.2.8p8
> +VER = ntp-4.2.8p15
> 
> include ../Makefile.defs
> 
> following is the diff for Patches
> 
> diff --git a/ntp/Patches/arc4random.patch b/ntp/Patches/arc4random.patch
> index 9335340..9b47948 100644
> --- a/ntp/Patches/arc4random.patch
> +++ b/ntp/Patches/arc4random.patch
> @@ -1,6 +1,5 @@
> -diff -ur lib/isc/random.c lib/isc/random.c
> ---- lib/isc/random.c 2014-12-19 11:56:53.000000000 +0000
> -+++ lib/isc/random.c 2015-04-08 21:02:23.301311839 +0000
> +--- lib/isc/random.c_orig 2020-12-15 09:40:25.156129286 +0000
> ++++ lib/isc/random.c 2020-12-15 09:42:27.787821312 +0000
> @@ -41,17 +41,6 @@
> static void
> initialize_rand(void)
> @@ -57,9 +56,8 @@ diff -ur lib/isc/random.c lib/isc/random.c
> }
> 
> isc_uint32_t
> -diff -ur sntp/libevent/arc4random.c sntp/libevent/arc4random.c
> ---- sntp/libevent/arc4random.c 2014-12-19 11:56:53.000000000 +0000
> -+++ sntp/libevent/arc4random.c 2015-04-08 20:59:41.424274901 +0000
> +--- sntp/libevent/arc4random.c_orig 2020-12-15 09:45:13.648770558 +0000
> ++++ sntp/libevent/arc4random.c 2020-12-15 09:46:37.956921662 +0000
> @@ -1,556 +0,0 @@
> -/* Portable arc4random.c based on arc4random.c from OpenBSD.
> 
> * * Portable version by Chris Davis, adapted for Libevent by Nick Mathewson
>     @@ -617,9 +615,8 @@ diff -ur sntp/libevent/arc4random.c sntp/libevent/arc4random.c
> * ```
>    return r % upper_bound;
>   ```
> 
> -}
> -#endif
> -diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
> ---- sntp/libevent/evutil_rand.c 2014-12-19 11:56:52.000000000 +0000
> -+++ sntp/libevent/evutil_rand.c 2015-04-08 21:07:25.994990893 +0000
> +--- sntp/libevent/evutil_rand.c_orig 2020-12-15 09:47:45.644374432 +0000
> ++++ sntp/libevent/evutil_rand.c 2020-12-15 09:53:16.489751822 +0000
> @@ -40,104 +40,26 @@
> #include "util-internal.h"
> #include "evthread-internal.h"
> @@ -727,7 +724,7 @@ diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
> return 0;
> }
> #endif
> -@@ -145,62 +67,21 @@
> +@@ -145,58 +67,17 @@
> static void
> evutil_free_secure_rng_globals_locks(void)
> {
> @@ -787,8 +784,3 @@ diff -ur sntp/libevent/evutil_rand.c sntp/libevent/evutil_rand.c
> }
> 
> void
> 
> * evutil_free_secure_rng_globals_(void)
> * {
>   --    evutil_free_secure_rng_globals_locks();
>   -+      evutil_free_secure_rng_globals_locks();
> * }
>   diff --git a/ntp/Patches/etcfix.patch b/ntp/Patches/etcfix.patch
>   index 3a10a6b..3fb21f9 100644
>   --- a/ntp/Patches/etcfix.patch
>   +++ b/ntp/Patches/etcfix.patch
>   @@ -1,6 +1,6 @@
>   ---- include/ntp_config.h.orig  Thu May 14 06:34:41 2009
>   -+++ include/ntp_config.h       Thu May 14 06:15:12 2009
>   -@@ -10,7 +10,7 @@
>   +--- include/ntp_config.h_orig  2020-12-15 09:59:29.608754176 +0000
>   ++++ include/ntp_config.h       2020-12-15 10:00:02.755717774 +0000
>   +@@ -15,7 +15,7 @@
>   */
>   #ifndef CONFIG_FILE
>   # ifndef SYS_WINNT
> 
> @@ -9,20 +9,20 @@
> 
> # else /* SYS_WINNT */
> # define CONFIG_FILE "%windir%\system32\drivers\etc\ntp.conf"
> # define ALT_CONFIG_FILE "%windir%\ntp.conf"
> ---- libntp/audio.c.orig Thu May 14 06:34:41 2009
> -+++ libntp/audio.c Thu May 14 06:15:12 2009
> -@@ -53,7 +53,7 @@
> +--- libntp/audio.c_orig 2020-12-15 10:01:01.291870014 +0000
> ++++ libntp/audio.c 2020-12-15 10:01:31.639741992 +0000
> +@@ -66,7 +66,7 @@
> static struct audio_device device; /* audio device ident _/ #endif /_ HAVE_SYS_AUDIOIO_H */
> #ifdef PCM_STYLE_SOUND
> -# define INIT_FILE "/etc/ntp.audio"
> +# define INIT_FILE "/etc/inet/ntp.audio"
> 
> * int agc =     SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE */
> * int monitor = SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
> * int devmask = 0;
>   ---- ntpdate/ntpdate.c.orig     Thu May 14 06:34:41 2009
>   -+++ ntpdate/ntpdate.c  Thu May 14 06:15:12 2009
>   -@@ -192,7 +192,7 @@
> 
> * static ioctl_arg_T agc                = SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE */
> * static ioctl_arg_T audiomonitor       = SOUND_MIXER_WRITE_VOLUME; /* or OGAIN */
>   +--- ntpdate/ntpdate.c_orig     2020-12-15 10:02:37.046065626 +0000
>   ++++ ntpdate/ntpdate.c  2020-12-15 10:03:04.849615327 +0000
>   +@@ -179,7 +179,7 @@
>   #ifndef KEYFILE
>   # ifndef SYS_WINNT
> 
> @@ -31,9 +31,9 @@
> 
> # else
> #define KEYFILE "%windir%\ntp.keys"
> 
> # endif /* SYS_WINNT */
> ---- ntpd/refclock_oncore.c 2015-01-03 03:47:48.000000000 +0000
> -+++ ntpd/refclock_oncore.c 2015-04-08 05:19:17.841550368 +0000
> -@@ -1211,7 +1211,7 @@
> +--- ntpd/refclock_oncore.c_orig 2020-12-15 10:03:48.326006011 +0000
> ++++ ntpd/refclock_oncore.c 2020-12-15 10:04:26.727103584 +0000
> +@@ -1213,7 +1213,7 @@
> 
> ```
>     FILE    *fd;
>     char    *cc, *ca, line[100], units[2], device[64];
> ```
> 
> diff --git a/ntp/Patches/monitor.patch b/ntp/Patches/monitor.patch
> deleted file mode 100644
> index b460db5..0000000
> --- a/ntp/Patches/monitor.patch
> +++ /dev/null
> @@ -1,29 +0,0 @@
> ---- libntp/audio.c Tue Jul 1 18:15:20 2014
> -+++ libntp/audio.c.orig Tue Jul 1 18:15:37 2014
> -@@ -55,7 +55,7 @@
> 
> * #ifdef PCM_STYLE_SOUND
> * # define INIT_FILE "/etc/inet/ntp.audio"
> * int agc =     SOUND_MIXER_WRITE_RECLEV; /* or IGAIN or LINE _/
>   --int monitor = SOUND_MIXER_WRITE_VOLUME; /_ or OGAIN _/
>   -+int audiomonitor =    SOUND_MIXER_WRITE_VOLUME; /_ or OGAIN */
> * int devmask = 0;
> * int recmask = 0;
> * char cf_c_dev[100], cf_i_dev[100], cf_agc[100], cf_monitor[100];
>   -@@ -334,7 +334,7 @@
> * ```
>             /* devmask */
>   ```
> * ```
>             i = mixer_name(cf_monitor, devmask);
>   ```
> * ```
>             if (i >= 0)
>   ```
> 
> -- monitor = MIXER_WRITE(i);
> -+ audiomonitor = MIXER_WRITE(i);
> 
> * ```
>             else
>   ```
> * ```
>                     printf("monitor %s not in devmask %#x\n",
>   ```
> * ```
>                            cf_monitor, devmask);
>   ```
> 
> -@@ -409,7 +409,7 @@
> 
> * # endif
> * ```
>             l |= r << 8;
>   ```
> * ```
>             if (cf_monitor[0] != '\0')
>   ```
> 
> -- rval = ioctl(ctl_fd, monitor, &l );
> -+ rval = ioctl(ctl_fd, audiomonitor, &l );
> 
> * ```
>             else
>   ```
> * ```
>                     rval = ioctl(ctl_fd, SOUND_MIXER_WRITE_VOLUME,
>   ```
> * ```
>                                  &l);
>   ```
> 
> diff --git a/ntp/Patches/openssl.patch b/ntp/Patches/openssl.patch
> index 5b2bda4..25383f8 100644
> --- a/ntp/Patches/openssl.patch
> +++ b/ntp/Patches/openssl.patch
> @@ -1,7 +1,7 @@
> ---- sntp/m4/ntp_openssl.m4.orig Tue Jul 1 19:32:31 2014
> -+++ sntp/m4/ntp_openssl.m4 Tue Jul 1 19:34:46 2014
> -@@ -66,6 +66,17 @@
> 
> * esac
>   +--- sntp/m4/ntp_openssl.m4_orig        2020-12-15 10:10:18.520857041 +0000
>   ++++ sntp/m4/ntp_openssl.m4     2020-12-15 10:12:11.138442468 +0000
>   +@@ -73,6 +73,17 @@
> 
> * case "$with_crypto:${PKG_CONFIG:+notempty}:${with_openssl_libdir-notgiven}:${with_openssl_incdir-notgiven}" in
>   no:*) ;;
> * sunw:*)
>   diff --git a/ntp/Patches/perl.patch b/ntp/Patches/perl.patch
>   index 8bef488..2f17110 100644
>   --- a/ntp/Patches/perl.patch
>   +++ b/ntp/Patches/perl.patch
>   @@ -1,6 +1,6 @@
>   ---- configure.ac       2014-07-02 20:25:10.231597249 +0000
>   -+++ configure.ac       2014-07-02 20:52:06.327098504 +0000
>   -@@ -131,12 +131,10 @@
>   +--- configure.ac_orig  2020-12-15 10:06:02.792818880 +0000
>   ++++ configure.ac       2020-12-15 10:08:29.547472840 +0000
>   +@@ -134,12 +134,10 @@
>   AC_ISC_POSIX
> 
> @@ -13,8 +13,8 @@
> AC_PATH_PROG([PATH_TEST], [test])
> AS_UNSET([ac_cv_path_PATH_TEST])
> test -z "$CONFIG_SHELL" && CONFIG_SHELL=/bin/sh
> -@@ -4302,7 +4300,30 @@
> 
> * AC_CONFIG_FILES([tests/ntpd/Makefile])
>   +@@ -4459,7 +4457,30 @@
> 
> * AC_CONFIG_FILES([tests/sec-2853/Makefile])
>   AC_CONFIG_FILES([util/Makefile])
> 
> -perllibdir="${datadir}/ntp/lib"

sorry for don't know how to past raw format for the patches

**Comment by danmcd** [comment]
If you have an on-github fork of illumos-joyent, you can create a pull request.  Also, I can take the patch and create an OS- ticket AND a proper pull-request a bit more easily if you'd like me to.

(And while I gotcha here, can you peek at https://github.com/joyent/illumos-extra/pull/44 which is a similar update-it-already change?)

**Comment by tozhu** [comment]
#44 is regarding to openssl, this issue is regarding to NTP, I don't think they are the same

and the testing is done.  test progress, testing screen dump and testing result is post on https://github.com/joyent/illumos-extra/pull/46

Please help to review and merge.

**Comment by tozhu** [comment]
close it since it is merged into the code repository
