### ISSUE TITLE
openssh: DisableBanner patch mis-merged in 8.6

### ISSUE THREAD

**Issue by arekinath** [joyent/illumos-extra#63]
Looks like there was a mistake in the DisableBanner patch on the 8.6 openssh update. The symbol `command` is a pointer now, not a static struct (since you can't do that with `sshbuf`). Pretty straightforward fix, thankfully.

**Comment by bahamat** [comment]
Fixed in cbf57f6c0f25f252cf9962930c68e897c76d379f
